<?php

namespace FixBundle\Repository;

use Symfony\Component\Validator\Constraints\Date;


/**
 * EvennementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvennementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findevenementprochain($date,$user)
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT e
        FROM FixBundle\Entity\Evenement e 
        WHERE e.date > :date AND e.nbplace > 0 AND  e.id not IN (SELECT IDENTITY(r.evennement) FROM FixBundle\Entity\Reservation r WHERE  r.user = :user) ORDER BY  e.date ASC'
        )->setParameters(array('date'=>$date,'user'=>$user) );

        // returns an array of Product objects
        return $query->execute();
    }
    public function findevenementbydate()
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT e
        FROM FixBundle\Entity\Evenement e 
        ORDER BY  e.date DESC'
        )->setParameters(array() );

        // returns an array of Product objects
        return $query->execute();
    }
    public function findevenement($date,$user)
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT e
        FROM FixBundle\Entity\Evenement e 
        WHERE e.date > :date AND e.nbplace > 0 AND  e.id  IN (SELECT IDENTITY(r.evennement) FROM FixBundle\Entity\Reservation r WHERE  r.user = :user)'
        )->setParameters(array('date'=>$date,'user'=>$user) );

        // returns an array of Product objects
        return $query->execute();
    }
    }

